### ISSUE TITLE
Error 'No CSS for file' with vite and tsconfig-paths

### ISSUE THREAD

**Issue by evertbouw** [vanilla-extract-css/vanilla-extract#1302]
### Describe the bug

I'm using `vite-tsconfig-paths`, in my tsconfig I have baseUrl set to `"./src"`, if I now import a file (`import "main.css";`), I get the error `[vite] Internal server error: No CSS for file: /Users/evert/Projects/vite-project/src/src/main.css.ts Plugin: vite:import-analysis`. For some reason it's got `/src/src/` which won't work. This worked fine with `@vanilla-extract/vite-plugin` < 4

### Reproduction

https://github.com/evertbouw/vanilla-extract-vite

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 1.41 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    pnpm: 8.15.1 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 121.0.6167.85
    Safari: 17.2.1
  npmPackages:
    @vanilla-extract/css: ^1.14.1 => 1.14.1 
    @vanilla-extract/vite-plugin: ^4.0.1 => 4.0.1 
    vite: ^5.0.8 => 5.0.12
```

### Used Package Manager

pnpm

### Logs

```shell
[commonjs--resolver] No CSS for file: /Users/evert/Projects/vite-project/src/src/main.css.ts
error during build:
Error: No CSS for file: /Users/evert/Projects/vite-project/src/src/main.css.ts
    at Object.getCssForFile (/Users/evert/Projects/vite-project/node_modules/.pnpm/@vanilla-extract+integration@6.4.0/node_modules/@vanilla-extract/integration/dist/vanilla-extract-integration.cjs.prod.js:833:15)
    at Object.resolveId (/Users/evert/Projects/vite-project/node_modules/.pnpm/@vanilla-extract+vite-plugin@4.0.1_vite@5.0.12/node_modules/@vanilla-extract/vite-plugin/dist/vanilla-extract-vite-plugin.cjs.prod.js:142:79)
    at file:///Users/evert/Projects/vite-project/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/es/shared/node-entry.js:18692:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///Users/evert/Projects/vite-project/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/es/shared/node-entry.js:18592:28)
    at async resolveId (file:///Users/evert/Projects/vite-project/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/es/shared/node-entry.js:17261:26)
    at async ModuleLoader.resolveId (file:///Users/evert/Projects/vite-project/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/es/shared/node-entry.js:17675:15)
    at async Object.resolveId (file:///Users/evert/Projects/vite-project/node_modules/.pnpm/vite@5.0.12/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:8141:10)
    at async PluginDriver.hookFirstAndGetPlugin (file:///Users/evert/Projects/vite-project/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/es/shared/node-entry.js:18592:28)
    at async resolveId (file:///Users/evert/Projects/vite-project/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/es/shared/node-entry.js:17261:26)
    at async ModuleLoader.resolveId (file:///Users/evert/Projects/vite-project/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/es/shared/node-entry.js:17675:15)
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agex-n7** [comment]
Same issue for me, baseUrl is also set to `./src` as well, but there seems to be an issue when trying to resolve the CSS files when used with storybook in particular.

When downgrading to `"@vanilla-extract/vite-plugin": "3.9.5"`, it works as expected.

**Comment by mrm007** [comment]
Thanks for reporting. I'll have a look this weekend. Just to confirm, have you tried the troubleshooting steps from https://github.com/aleclarson/vite-tsconfig-paths/wiki/Troubleshooting?

@agex-n7 can you share a reproduction for your case? It would help to have more test cases.

**Comment by mrm007** [comment]
I have a fix ready which works with https://github.com/evertbouw/vanilla-extract-vite.
Can you please test in your own repos with [this snapshot version]?

[this snapshot version]: https://github.com/vanilla-extract-css/vanilla-extract/actions/runs/7766286837

**Comment by agex-n7** [comment]
Can confirm, it solved it for me as well. Sorry for the late reply.

**Comment by tombohub** [comment]
I don't understand, do I need to do something or just install vite plugin? It doesn't work for me

**Comment by askoufis** [comment]
> I don't understand, do I need to do something or just install vite plugin? It doesn't work for me

@tombohub The fix was in the vite plugin, so just updating it to the latest version should fix this particular issue. If you've encountered a separate issue, please raise an issue with a reproduction.

**Comment by tombohub** [comment]
@askoufis I did I've installed yesterday fresh package vanilla-extract and vanilla-vite-plugin to try it out, but got this error.

I can try one more time?

**Comment by evertbouw** [comment]
@tombohub simply running `pnpm upgrade` is sufficient to resolve the error in the reproduction

**Comment by askoufis** [comment]
> @askoufis I did I've installed yesterday fresh package vanilla-extract and vanilla-vite-plugin to try it out, but got this error.
> 
> I can try one more time?

I can't reproduce the issue on a fresh `npm create vite` with the `react-ts` template. Just installing the vite plugin and VE, and adding a simple style works fine. If you can reproduce it, please make an separate issue.

**Comment by re1sub** [comment]
I still have this problem, weirdly. I'm mainly on my Linux machine where I never encountered the problem in my SolidJS + TS + Vite + tsConfigPaths project, but I'm dual booting on Windows and right now on windows the same project freshly cloned and installed gives me the error, only downgrading to 3.9.5 solves the issue

**Comment by askoufis** [comment]
@re1sub If it's a windows-only issue then it could be a path that the plugin isn't normalizing or something. If you can still reproduce it with v5 of the vite plugin, a minimal reproduction of your issue would help me diagnose the bug.

**Comment by re1sub** [comment]
@askoufis Hi! I created the repo with the issue. You can read the README to learn more. 

https://github.com/re1sub/issue-1302-repro/tree/main

**Comment by askoufis** [comment]
@re1sub I reproduced your issue on windows, but couldn't fix it in Vanilla Extract. However, I checked the `vite-tsconfig-paths` repo and found https://github.com/aleclarson/vite-tsconfig-paths/issues/212 which seemed like it was the same issue in your repo. Sure enough the proposed fix addresses your issue.

There isn't a PR open with the fix yet, so you could open it yourself if you want. I don't have time right now to raise a PR, but I can do it tomorrow if no one else gets to it.

**Comment by re1sub** [comment]
@askoufis thanks for doing the PR, sorry I didn't have time, but it seems to me that that was the issue and using `isAbsolute` should fix it
